### ISSUE TITLE
An invite to do a talk @ PHPMiNDS 

### ISSUE THREAD

**Issue by pavlakis** [rectorphp/the-power-of-automated-refactoring-feedback#1]
Hi both

following on from my tweet: https://twitter.com/pavlakis/status/1394262352028131335?s=20 
I would like to invite you both to do a talk @ PHPMiNDS.

We are a UK-based PHP User Group meeting on the 2nd Thursday of the month at 18:30 BST.
There are dates available from Thursday 12th August onwards.

It will be great to have you over. 

Thanks 🙏🏻

**Comment by matthiasnoback** [comment]
@pavlakis @TomasVotruba I can't make it on August 12th, but I guess the next opportunity is September 9th and would work.

**Comment by pavlakis** [comment]
Thanks both.
The September 9th date works too.

@matthiasnoback @TomasVotruba Are you both available on that day?

**Comment by TomasVotruba** [comment]
I hope by that date it would be possible to do it person :)

It's pretty far for me to say for sure, but at the moment I'm available :+1:

**Comment by pavlakis** [comment]
Thanks @TomasVotruba  🙏 

We'll most likely still be doing the meetup online at the time. I'll follow up in August then.

**Comment by matthiasnoback** [comment]
Great, I'll mark the date as well!

**Comment by pavlakis** [comment]
Hi @matthiasnoback  and @TomasVotruba 

As we are one month away from the meetup, can you provide us with a talk title and an abstract?

Thanks

**Comment by pavlakis** [comment]
Hi @matthiasnoback and @TomasVotruba can we continue this conversation on Twitter DM's or email?

Please follow me on the UG's Twitter account: https://twitter.com/phpminds

Or my personal one: https://twitter.com/pavlakis

And we can exchange emails there or follow up on DMs.

Thank you 🙏

**Comment by TomasVotruba** [comment]
I'm kind of busy right now with personal stuff. Can you ping me here on Friday? I'll provide neccessery details then :)

**Comment by matthiasnoback** [comment]
Here's a description that can be used for the meetup announcement, is this something you can work with @pavlakis ?

Title: The Power of Automated PHP Refactoring

Abstract: In this talk Matthias Noback and Tomas Votruba, the authors of the book "Rector - The power of automated refactoring", will tell you what Rector is, how you can use this tool, and what amazing things you can achieve with it. You'll get a taste of Rector and how it can be used in everyday situations to move your code forward. We'll take time to answer questions from the audience as well.

**Comment by pavlakis** [comment]
That's perfect. Thank you @matthiasnoback and @TomasVotruba

**Comment by pavlakis** [comment]
Thank you @matthiasnoback  and @TomasVotruba for doing the talk @ PHPMiNDS yesterday.
A very informative and enjoyable session.

Here is the link to the recording: 
https://www.youtube.com/watch?v=2pUwOtEWSkM
