### ISSUE TITLE
broken use statement on page 62

### ISSUE THREAD

**Issue by oceanicpanda** [rectorphp/the-power-of-automated-refactoring-feedback#11]
# Code Improvement

I found a glitch on page 62

**I propose this change**

```diff
-before
use Symfony\Component\DependencyInjection\Loader\Configurator\Container\
Configurator;
+after
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
```
Otherwise one receives the error:
[ERROR] Argument 1 passed to                                                                                    
         RectorPrefix20210518\Symfony\Component\DependencyInjection\Loader\ProtectedPhpFileLoader::{closure}()   
         must be an instance of ContainerConfigurator, instance of                                               
         RectorPrefix20210518\Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator    
         given, called in                                                                                        
         /server/code/rector/vendor/rector/rector/vendor/symfony/dependency-injection/Loader/PhpFileLoader.php on
         line 43  

Thanks!

**Comment by TomasVotruba** [comment]
Thanks, I think we've fixed this in one of recent releases :+1:

**Comment by matthiasnoback** [comment]
Yes, but there's one other issue: some lines will be cut off with an extra backslash because it's simply too long to show on the page. We have no control over that, so the reader should still be cautious when copy-pasting code.
