### ISSUE TITLE
Example custom rector needs another composer require

### ISSUE THREAD

**Issue by oceanicpanda** [rectorphp/the-power-of-automated-refactoring-feedback#12]
# Code Improvement

I think code on page 58 could be improved: the command "vendor/bin/php-parse src/before.php --var-dump" is given at the end of the page but nowhere has it been specified yet to require this package.

**Why?**

For the sake of completeness and understanding.

Thanks!

**Comment by TomasVotruba** [comment]
Thank you, we'll add the `composer require` line before this one :+1:
