### ISSUE TITLE
missing output page 76

### ISSUE THREAD

**Issue by oceanicpanda** [rectorphp/the-power-of-automated-refactoring-feedback#14]
# Text Improvement

I think text on page 76 could be improved:

**Why?**

The results of 
echo $today->format('Y-m-d'), "\n";
echo $nextMonday->format('Y-m-d'), "\n";
are not provided in the text so it is not clear to the reader without them typing in the code itself what the results will be.

**I propose this change**

```diff
-before
no output is given
+after
output for the 2 method calls are show beneath.
```

Thanks!

**Comment by TomasVotruba** [comment]
Hi, I'm not sure where exactly is this and what should be added where.

Could you provide more context? E.g. screenshot of text before/after and what do you want to exactly add where? 

Thank you

**Comment by matthiasnoback** [comment]
I've looked this up and the text already explains what the output will be: "running this script will just output the same date twice." (the output would be different every day, so I didn't show it in the text).

**Comment by matthiasnoback** [comment]
Thanks for submitting this issue though. Closing it now since I don't think we can improve this.
