### ISSUE TITLE
extra namespace item

### ISSUE THREAD

**Issue by oceanicpanda** [rectorphp/the-power-of-automated-refactoring-feedback#16]
# Code Improvement

I think code on page 86 could be improved:

**Why?**

Because in the example test.php given the namespace is shown as "namespace FindingNodeCandidates" but the dumped node has 2 elements in the "parts" array.

["parts"] => array(2) {
[0] => "TestDrivenRuleDevelopment"
[1] => "FindingNodeCandidates"
}

**I propose this change**

```diff
-before
["parts"] => array(2) {
[0] => "TestDrivenRuleDevelopment"
[1] => "FindingNodeCandidates"
}
+after
["parts"] => array(2) {
[0] => "FindingNodeCandidates"
}
```

Thanks!

**Comment by TomasVotruba** [comment]
Thank you! It's fixed now :+1:

**Comment by matthiasnoback** [comment]
This was fixed, but the code generation tool added it back the next time we ran it ;) I've now made a permanent fix for this.
