### ISSUE TITLE
composer require phpunit/phpunit command missing

### ISSUE THREAD

**Issue by oceanicpanda** [rectorphp/the-power-of-automated-refactoring-feedback#19]
# Code Improvement

I think code on page 82 could be improved: the composer require phpunit/phpunit command is missing, for the sake of completeness it would be good to have. Further I'm running php 7.4.18, rector-prefixed (0.10.21), and the php-unit (8.5.15) that I need to use for my project, it would appear there is an incompatibility somewhere. When I try to run the sample test as given in the text I run into the following error:

_HumbugBoxe5640220fe34\Nette\DI\ServiceCreationException : Service 'regexGrammarStream': Undefined offset: 0
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Resolver.php:342
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Resolver.php:60
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerBuilder.php:231
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Compiler.php:199
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Compiler.php:159
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php:99
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php:65
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php:34
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/Configurator.php:35
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/bootstrap/src/Bootstrap/Configurator.php:160
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/ContainerFactory.php:65
 /project/include/vendor/rector/rector-prefixed/packages/NodeTypeResolver/DependencyInjection/PHPStanServicesFactory.php:37
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:6172
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:971
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:5990
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:5928
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:6050
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:5922
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:6036
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:5917
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:6022
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:5912
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:5968
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:5907
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:5954
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:5902
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:5940
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:5897
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:3437
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:6451
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:6182
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:2727
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:2737
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:2707
 /project/include/vendor/rector/rector-prefixed/vendor/symfony/dependency-injection/Container.php:221
 /project/include/vendor/rector/rector-prefixed/vendor/symfony/dependency-injection/Container.php:204
 /project/include/vendor/rector/rector-prefixed/packages/Testing/PHPUnit/AbstractTestCase.php:53
 /project/include/vendor/rector/rector-prefixed/packages/Testing/PHPUnit/AbstractRectorTestCase.php:62
 
 Caused by
 PHPUnit\Framework\Error\Notice: Undefined offset: 0
 
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/vendor/hoa/protocol/Protocol.php:97
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/vendor/hoa/protocol/Protocol.php:73
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/vendor/hoa/protocol/Protocol.php:85
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/vendor/hoa/stream/Stream.php:530
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/vendor/hoa/consistency/Autoloader.php:162
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/vendor/hoa/consistency/Autoloader.php:104
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/vendor/hoa/file/Generic.php:47
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/vendor/hoa/file/File.php:48
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/vendor/hoa/file/Read.php:47
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Resolver.php:109
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Definitions/ServiceDefinition.php:141
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Resolver.php:55
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerBuilder.php:231
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Compiler.php:199
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Compiler.php:159
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php:99
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php:65
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerLoader.php:34
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/Configurator.php:35
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/bootstrap/src/Bootstrap/Configurator.php:160
 phar:///project/include/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/ContainerFactory.php:65
 /project/include/vendor/rector/rector-prefixed/packages/NodeTypeResolver/DependencyInjection/PHPStanServicesFactory.php:37
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:6172
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:971
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:5990
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:5928
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:6050
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:5922
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:6036
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:5917
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:6022
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:5912
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:5968
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:5907
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:5954
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:5902
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:5940
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:5897
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:3437
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:6451
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:6182
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:2727
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:2737
 /tmp/rector/cache/Container9HcfIxf/Rector_Core_HttpKernel_RectorKernelTest_b5add545b32eecac4dc5f3cbbf3d6ae2DebugContainer.php:2707
 /project/include/vendor/rector/rector-prefixed/vendor/symfony/dependency-injection/Container.php:221
 /project/include/vendor/rector/rector-prefixed/vendor/symfony/dependency-injection/Container.php:204
 /project/include/vendor/rector/rector-prefixed/packages/Testing/PHPUnit/AbstractTestCase.php:53
 /project/include/vendor/rector/rector-prefixed/packages/Testing/PHPUnit/AbstractRectorTestCase.php:62
 

Time: 1.01 seconds, Memory: 46.50 MB

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.

Process finished with exit code 2

is it possible to install an up-to-date phpunit that is only used by rector-prefixed?

Thanks!

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.
I'm not sure how to reproduce to have a similar problem.

Could you provide full script to reproduce?

Also, be sure to use Rector 0.11+

**Comment by matthiasnoback** [comment]
I have added your suggestion about installing PHPUnit, thanks.

**Comment by oceanicpanda** [comment]
I updated PHPUnit and still see the error above.

phpunit.xml:
<?xml version="1.0" encoding="UTF-8"?>
<phpunit bootstrap="rector_bootstrap.php"
         colors="true">
    <testsuites>
        <testsuite name="Rectortests">
            <directory>/project/utils/rector/tests/Rector/AddMyTypeRector</directory>
        </testsuite>
    </testsuites>
</phpunit>

rector_bootstrap.php:
<?php
$files = [
    dirname(__DIR__).'/AddMyTypeRector/AddMyTypeRectorTest.php',
];

foreach ($files as $file) {
    if (file_exists($file)) {
        require_once $file;
    }
}

folder structur:
utils
    /rector
        /src
            /Rector
                /AddMyTypeRector.php
        /tests
            /Rector
                /AddMyTypeRector
                    /config
                        /config.php
                    /Fixtures
                        /method-with-my-type.php.inc
                    AddMyTypeRectorTest.php

method-with-my-type-php.inc:
<?php

namespace Utils\Rector\Tests\Rector\AddMyTypeRector\Fixture;

use Project\tables;

class ClassWithTableParameter
{
    /**
     * @param table $tbl
     */
    public function get_table_object($tbl)
    {
    }
}
?>
-----
<?php

namespace Utils\Rector\Tests\Rector\AddMyTypeRector\Fixture;

use Project\tables;

class ClassWithTableParameter
{
    public function get_table_object(table $tbl)
    {
    }
}
?>

config.php:
<?php

declare(strict_types=1);

use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Utils\Rector\Rector\AddMyTypeRector;

return static function (
    ContainerConfigurator $containerConfigurator
): void {
    $services = $containerConfigurator->services();
    $services->set(AddMyTypeRector::class);
};

The AddMyRector.php file is an empty template copied the book (UseDateTimeImmutableRector) and the relevant class name changed and the rector test class has also been copied from the book.

**Comment by TomasVotruba** [comment]
Thanks for reaching out. This would hard to debug back and forth without real code.
Could you create a repository on Github and link it here? I'll check what is wrong :)
