### ISSUE TITLE
Yes, we a have the technology to change the PHP world.

### ISSUE THREAD

**Issue by esurov** [rectorphp/the-power-of-automated-refactoring-feedback#2]
# Text Improvement

I think text on page iv could be improved:

**Why?**

It's just a typo I guess. Or an editing issue.

**I propose this change**

```diff
-Yes, we a have the technology to change the PHP world.
+Yes, we have the technology to change the PHP world.
```

Thanks!

**Comment by TomasVotruba** [comment]
Thanks! Fixed it :+1:
