### ISSUE TITLE
PDF filesize

### ISSUE THREAD

**Issue by staabm** [rectorphp/the-power-of-automated-refactoring-feedback#3]
I am wondering whether there are some low hanging fruits to get regarding the books filesize.

the PDF I downloaded has ~133MB. having a smaller file would ease handling with the file, decrease download time and require less resources on the reading device, so it could even be read on an old android tablet or similar

**Comment by TomasVotruba** [comment]
Thanks! 
Any ideas what is taking so much space? Text should fit a few kb.

**Comment by staabm** [comment]
it seems there is nearly no text in the PDF. almost all the content is rendered as a big image/graphic

**Comment by TomasVotruba** [comment]
I've just downloaded PDF and it has ~850 kb.

Could you send the PDF on my email tomas.vot@gmail.com? How exactly have you downloaded it? Screens would be awesome to find out, what glitch is going on where :)

**Comment by TomasVotruba** [comment]
We could not reproduce this issues and I haven't recieved any email from you.

Matthias told me this might be caused by accidentaly "printing PDF" from the browser. So make sure the file is downloaded directly :+1:
