### ISSUE TITLE
Question about visitors

### ISSUE THREAD

**Issue by joelclermont** [rectorphp/the-power-of-automated-refactoring-feedback#30]
On page 30, it shows two rounds of traversal, the first with the `NodeConnectingVisitor`, and the second with our `EchoMethodClassNodeVisitor`:

```php
// First round: connect the nodes
$traverser = new NodeTraverser();
$traverser->addVisitor(new NodeConnectingVisitor());
$traverser->traverse($statements);

// Second round: show some information
$traverser = new NodeTraverser();
$traverser->addVisitor(new EchoMethodClassNodeVisitor());
$traverser->traverse($statements);
```

I tried the code just adding both visitors to the same traverser, and I got the same expected output. 

```php
$traverser = new NodeTraverser();
$traverser->addVisitor(new NodeConnectingVisitor());
$traverser->addVisitor(new EchoMethodClassNodeVisitor());
$traverser->traverse($statements);
```

Is there a reason to have this done in two separate passes? I'm guessing that maybe certain node connections may not be fully wired up if we attach a second visitor in the same pass, but I'd like to know for sure. Thanks!

**Comment by TomasVotruba** [comment]
Hi, that's a great question!

In most common cases, it's better to use single NodeTravserser, for better performance.

E.g. native Rector rules registered in `rector.php` are all added to single NodeTravser:

```php
$traverser = new NodeTraverser();
$traverser->addVisitor(new FirstRector());
$traverser->addVisitor(new SecondRector());
$traverser->addVisitor(new ThirdRector());

$traverser->traverse($statements);
```

<br>

There is just one exception that is concered internal Rector run. If you need to decorate nodes with attributes (e.g. `$node->setAttribute('class_node', ...))` in `FirstNodeVisitor` and you want to work with them in `SecondNodeVisitor` (e.g. `$node->getAttribute('class_node')`), they have to be run in 2 separated `traverse()` waves.

A great example is a service in Rectorcode that prepares connected nodes, parent nodes, class names, parent class methods etc.:
https://github.com/rectorphp/rector-src/blob/88559e002b588102ef53cb49803db4283fe304b9/packages/NodeTypeResolver/NodeScopeAndMetadataDecorator.php#L40-L82

**Comment by joelclermont** [comment]
Very helpful, thank you!
