### ISSUE TITLE
Sentence never ends

### ISSUE THREAD

**Issue by yann-eugone** [rectorphp/the-power-of-automated-refactoring-feedback#32]
# Glitch

I found glitch on page 130

**I can't propose a change but**

```diff
-. This is how you
+. This is how you ...
```

Thanks!

**Comment by TomasVotruba** [comment]
Hi, thanks for the diff changes! It seems both strings are equal here. What exactly should change?

Btw, we usually fix these by search and replace in a whole book, and sometimes it helps to have more words around it to have only 1 unique item in a book to fix. Could you provide more words, e.g. 5-10? Thanks!

**Comment by yann-eugone** [comment]
Hum sorry. I wasn't clear enough I **can't** propose a change, because I can't tell what you whishes to say here.
The sentence starts with these words but never ends...

On page 130 the context is 

```
or import it with a use statement. This is how you
Given that we already have a configuration file for the rule set,
```

**Comment by TomasVotruba** [comment]
Ah, I see :) so there are some words missing. We'll check it, thanks, this is good enough :+1:

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting. We've just included your fix in the book :+1:
