### ISSUE TITLE
An invite to do a talk @ phpugmrn

### ISSUE THREAD

**Issue by shochdoerfer** [rectorphp/the-power-of-automated-refactoring-feedback#33]
Following my [tweet](https://twitter.com/shochdoerfer/status/1410317563330969602), I would love to have you speak at the next [phpugmrn](https://www.meetup.com/de-DE/PHPUG-Rhein-Neckar/events/275304499/) event on the 26th of August.

The topic could be either Rector, the book, or both. I am open for suggestions :)

**Comment by matthiasnoback** [comment]
Thanks for the invitation @shochdoerfer August 26th works for me, what about you, @TomasVotruba ? I won't have a lot of time to prepare a rehearsed talk, but I'm sure Tomas and I can come up with a format that works and is interesting for everyone.

**Comment by shochdoerfer** [comment]
Awesome! No need to prep a rehearsed talk, I'll take what I can get from you people :P

**Comment by TomasVotruba** [comment]
26th August is fine for me :)

I think we'll improvise and show a small demo following Q&A.

**Comment by matthiasnoback** [comment]
Yeah, I think it's great to do a demo, I'll make sure to have some interview questions ready so we can always ask each other some things of interest. We'd still want to look like professionals ;)

**Comment by shochdoerfer** [comment]
Thanks! If you need someone asking stupid questions, I am happy to help out :P

Anything else you need from my side?

**Comment by shochdoerfer** [comment]
No way out, I have just announced the meetup on Meetup https://www.meetup.com/de-DE/PHPUG-Rhein-Neckar/events/275304499/ :)

Will start sending out annoying promotional tweets in the next couple of weeks...

**Comment by matthiasnoback** [comment]
Forgot to close this, see you some other time @shochdoerfer !
