### ISSUE TITLE
Copying the code doesn't work well

### ISSUE THREAD

**Issue by gauravmak** [rectorphp/the-power-of-automated-refactoring-feedback#35]
When I copy the code from the pdf file, the formatting is broken. The use statements are completely off. Sample attached. (Page no 29)

![Screenshot-from-2021-07-05-20-27-13](https://user-images.githubusercontent.com/11887260/124490243-7ec8f500-ddcf-11eb-95b0-5a66325c253b.png)

Loving the book so far, thanks.

**Comment by TomasVotruba** [comment]
Thanks for reporting :+1: 

<br>

This seems broken just for the linked file:

![Peek 2021-07-07 01-41](https://user-images.githubusercontent.com/924196/124679545-e876fb00-dec4-11eb-9dee-c05b6598aa1e.gif)

For other files the imports are quite allright:

![Peek 2021-07-07 01-42](https://user-images.githubusercontent.com/924196/124679568-f4fb5380-dec4-11eb-874b-fdd113ad7c5c.gif)


<br>

@matthiasnoback This might be some glitch in Leanpub. What do you think?

**Comment by TomasVotruba** [comment]
Hi, I'm dealing with suggestions before book for Rector 0.19 release next week.

I've tried to copy-paste the file contents and works well now :+1:
