### ISSUE TITLE
Creating a new object of NodeTraverser

### ISSUE THREAD

**Issue by gauravmak** [rectorphp/the-power-of-automated-refactoring-feedback#36]
# Code Improvement

I think the code on page 30 could be improved:

**Why?**

It is not required to create another instance of the `NodeTraverser` before the second round, right?
I am surprised that it works whether we keep that line or not.

Curious - Is the node connecting stuff kept somewhere in the memory? It isn't tied to the first instance?

**I propose this change**

```diff
+// First round: connect the nodes
+$traverser = new NodeTraverser();
+$traverser->addVisitor(new NodeConnectingVisitor());
+$traverser->traverse($statements);
+// Second round: show some information
-$traverser = new NodeTraverser();
+$traverser->addVisitor(new EchoMethodClassNodeVisitor());
+$traverser->traverse($statements);
```

Thanks!

**Comment by TomasVotruba** [comment]
Hi, thanks for suggestion :+1: 

This is rather incidental, as node visitors can collide and actually depend on each other.  The best practise is to keep them separate to remove space for any conflicts.

There are actually 3 standalone NodeTraverser instances in Rector itself to avoid such collisions.

See https://github.com/rectorphp/the-power-of-automated-refactoring-feedback/issues/30#issuecomment-864597558

**Comment by TomasVotruba** [comment]
> Is the node connecting stuff kept somewhere in the memory?

To your question, every node has an attribute array, where we can store data for later use.
That's why the node still keeps the metadata even after traversing.
