### ISSUE TITLE
Incomplete sentence

### ISSUE THREAD

**Issue by gauravmak** [rectorphp/the-power-of-automated-refactoring-feedback#41]
# Text Improvement

I think the text on page 130 could be improved:

**Why?**

Seems like there is an incomplete sentence.

`It then relies on the global setting called “auto-import names” to either leave the name as it is, or import it with a use statement. This is how you`

There is nothing after _how you_...

Thanks!

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting. We've just included your fix in the book :+1:
