### ISSUE TITLE
Next chapter announcement

### ISSUE THREAD

**Issue by arie-piscator** [rectorphp/the-power-of-automated-refactoring-feedback#44]
# Text Improvement

I think the text on page 37 (at the end of Programmatically Modifying PHP Code) could be improved:

**Why?**

Because an announcement is made that the next chapter will be about creating our first Rector rule. However, the second chapter is about PHP Tools in the Game, the third chapter about Creating Your First Rector Rule.

**I propose this change**

```diff
-before
We’ll do the latter in the next chapter when we create our first Rector rule.
+after
We’ll do the latter after the next chapter when we create our first Rector rule.
```

Thanks!

**Comment by TomasVotruba** [comment]
Thank you for your feedback. I put it into book just now :)
