### ISSUE TITLE
Invitation to speak at php-wvl.be

### ISSUE THREAD

**Issue by coudenysj** [rectorphp/the-power-of-automated-refactoring-feedback#46]
We would like to invite you to speak at one of our PHP-WVL meetups.

I already reached out to @matthiasnoback, but our next meetup date (12/10) doesn't fit is his agenda.

Any chance one of the following dates would work?

* 23/11
* 4/1
* 15/2
* 29/3

**Comment by TomasVotruba** [comment]
Hi, this is amazing. Do you mean online or offline? :)

**Comment by matthiasnoback** [comment]
November 23rd would be great. For me it'll be online anyway ;)

**Comment by TomasVotruba** [comment]
Great :) 23/11 is good for me too :+1: booked!

**Comment by coudenysj** [comment]
Awesome! Thank you guys! Looking forward to it.

**Comment by coudenysj** [comment]
Do you have a little abstract and bios you want us to put on the meetup page?

https://www.meetup.com/php-wvl/events/280987922/

**Comment by TomasVotruba** [comment]
Could this be re-used maybe :)
https://github.com/rectorphp/the-power-of-automated-refactoring-feedback/issues/33

**Comment by matthiasnoback** [comment]
This works better I think, we never sent Stephaj a good text...

Title: The Power of Automated PHP Refactoring

Abstract: In this talk Matthias Noback and Tomas Votruba, the authors of
the book "Rector - The power of automated refactoring", will tell you what
Rector is, how you can use this tool, and what amazing things you can
achieve with it. You'll get a taste of Rector and how it can be used in
everyday situations to move your code forward. We'll take time to answer
questions from the audience as well.

**Comment by matthiasnoback** [comment]
@coudenysj can you DM me the link for the video call? Looking forward to the meetup!

Copied from: https://www.meetup.com/php-wvl/events/nphhxmyccpbfc/

19:30 - 20:00: Welkom & Drankjes
20:00 - 20:10: Intro PHP-WVL
**20:15 - 21:15: The Power of Automated PHP Refactoring**
21:15 - ... : Raffle & Socializen

In this talk Matthias Noback and Tomas Votruba, the authors of
the book "Rector - The power of automated refactoring", will tell you what
Rector is, how you can use this tool, and what amazing things you can
achieve with it. You'll get a taste of Rector and how it can be used in
everyday situations to move your code forward. We'll take time to answer
questions from the audience as well.
