### ISSUE TITLE
Skipping Single-script fixtures?

### ISSUE THREAD

**Issue by marcitqualab** [rectorphp/the-power-of-automated-refactoring-feedback#47]
# Text Improvement

I think the text on page 93 could be improved:

"Fixtures that contain only a single script are examples of code that your
rule should “skip”, so the Rector project itself uses the convention to start
these fixtures with skip- as well."

**Why?**

Because it is hard to understand, it isn't very clear. 

I am not able to understand properly this text to provide a proposal. 
My question is. If the fixture has the example code to be tested against the rule and this fixture is skipped (so not runner against de rule) then the test is always going to pass as the rule will not be executed and the fixture will always be the same?
I think I am missing something here and the definition of the key point above does explain well this point.

Thanks!

**Comment by matthiasnoback** [comment]
Thanks for providing this feedback, we'll make sure to process this in the next update of the book!
