### ISSUE TITLE
Add `exclude-from-classmap` composer config

### ISSUE THREAD

**Issue by kynx** [rectorphp/the-power-of-automated-refactoring-feedback#48]
# Text Improvement

I think a note should be added to the Test Driven Rule Development chapter about avoiding problems with composer's classmap when `optimize-autoloader` is set to `true`. Maybe after the "Is it Okay if SomeOtherClass Doesn’t Actually Exist” note (sorry, I've got the epub, so page numbers don't really make sense). Or maybe just add the config below in the “Where to Store Your Rule Classes” note.

**Why?**

Composer's `dump-autoload` command will barf all over the fixtures without some additional configuration.

**I propose this change**

Composer commands might not like your fixtures and start throwing warnings like:
```
“Utils\Rector\Tests\Rector\UseDateTimeImmutableRector\Fixture\SomeOtherClass" located in “utils/rector/tests/Rector/UseDateTimeImmutableRector/Fixture/skip-other-names.php.inc” does not comply with psr-4 autoloading standard. Skipping."
```

This probably means you've got Composer's `optimise-autoloader` config set to `true`. It's easy to stop it trying to add your fixtures to the classmap: just add an `exclude-from-classmap` entry to `composer.json`:

```
    "autoload-dev": {
        "exclude-from-classmap": [
            "/utils/rector/tests/**/Fixture"
        ],
        "psr-4": {
            "Utils\\Rector\\": "utils/rector/src",
            "Utils\\Rector\\Tests\\": "utils/rector/tests"
        }
    },
```

Thanks!

**Comment by matthiasnoback** [comment]
Great idea! @TomasVotruba have you dealt with this before?

**Comment by TomasVotruba** [comment]
Hi, I'm looking into this when upgrading book to Rector 0.19. This is composer specific knowledge, that comes with enabling the option by developer. We do not mention the "optimise-autoloader" in the book, so it's out of our control so we'll keep it.

Based on my experience, it's better to optimize autoload only in production build, not in dev, to avoid slow loading locally and other unexpected behaviors.

Thanks
