### ISSUE TITLE
Code Improvement page 97

### ISSUE THREAD

**Issue by neveldo** [rectorphp/the-power-of-automated-refactoring-feedback#54]
# Code Improvement

I think code on page 97 could be improved:

**Why?**

This is not really a mistake I guess, but in the code snippet from this page, you use `$rectorConfig->services()->set()` to load a rule whereas `$rectorConfig->rule()` is used everywhere else in the book.

**I propose this change**

```diff
-    $rectorConfig->services()
-        ->set(CaptureReturnValueRector::class);
+    $rectorConfig->rule(CaptureReturnValueRector::class);
```

Thanks!

**Comment by TomasVotruba** [comment]
This should be gone by next release :+1:
