### ISSUE TITLE
PHP-Backporter - Is noW deprecated

### ISSUE THREAD

**Issue by esurov** [rectorphp/the-power-of-automated-refactoring-feedback#7]
# Text Improvement

I think the text on page 45 could be improved:

**Why?**

Because the library has not been updated for the last 10 years. I guess you just made a typo there.

**I propose this change**

```diff
-Is not deprecated
+Is now deprecated
```

Thanks!

**Comment by TomasVotruba** [comment]
Thank you, I've just fixed it in the book :hugs:
